// // This file is automatically generated and should not be edited.
// // It contains Firebase configuration for your Flutter app.

// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     // Add your platform-specific Firebase configuration here.
//     // The following is just an example; replace with actual configuration.
//     return const FirebaseOptions(
//       apiKey: 'AIzaSyDat7BIK8EBu-aMPZVqFQRlb9Puxj4FMM4',
//       appId: '1:478483318019:android:117f87926f5931afd8d536',
//       messagingSenderId: '478483318019',
//       projectId: 'finalbaraf',
//       storageBucket: 'https://console.firebase.google.com/project/finalbaraf/storage/finalbaraf.appspot.com/files'
//     );
//   }
// }
